import OIG2 from "./img/OIG2.jpg";

function generateHome () {
    const homePage = document.createElement('div');
    const infoDiv = document.createElement('div');
    const homeTitle = document.createElement('h1');
    homeTitle.textContent = "Absolutely real human food!"
    const homeText = document.createElement('p');
    homeText.textContent = "Welcome to the absolutely real food restaurant. All of this food is real. Definitely not generated by AI. You can consume it like a real human being would because this is a real restaurant."
    const foodImg = document.createElement('img');
    foodImg.src = OIG2;

    infoDiv.appendChild(homeTitle);
    infoDiv.appendChild(homeText);
    infoDiv.appendChild(foodImg);

    homePage.appendChild(infoDiv);

    return homePage;
}

export default generateHome;